org: muhammedmirza
app: leaderboard
service: leaderboard
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  matchResult:
    handler: src/matchResult.handler
    events:
      - httpApi:
          path: /matchResult
          method: post
  leaderboard:
    handler: src/leaderboard.handler
    events:
      - httpApi:
          path: /leaderboard
          method: get

plugins:
  - serverless-offline
