org: muhammedmirza
app: leaderboard
service: leaderboard
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  matchResult:
    handler: src/matchResult.handler
    events:
      - httpApi:
          path: /matchResult
          method: post

plugins:
  - serverless-offline
